name: Publish utility on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build zips
    runs-on: ubuntu-latest
    steps:

      - name: '📄 Checkout'
        uses: actions/checkout@v3

      - name: '📦 Package Windows'
        run: |
          cd ${{github.workspace}}/windows
          cp -r ../FILTERS .
          zip -r windows.zip .
          gh release upload ${{github.event.release.tag_name}} windows.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

      - name: '📦 Package SteamOS'
        run: |
          cd ${{github.workspace}}/steamos
          cp -r ../FILTERS .
          zip -r steamos.zip .
          gh release upload ${{github.event.release.tag_name}} steamos.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
